#!/bin/bash
#
# use this script to add a user on the local system
# you must supply a username as a argument to the script
# you can also provide a comment (optional)
# passwords will be autogenerated
# and displyed at the output

if [[ "${UID}" -ne 0 ]]
then
  echo "this must be run as with sudo or as root"
  exit 1
fi

# note to usage-
if [[ "${#}" -lt 1 ]]
then
  echo "Usage: ${0} USERNAME [COMMENT]..."
  echo 'Create an account on the local system with the name of USERNAME and a comment field of COMMENT.'
  exit 1
fi

# Argument > parameter of USERNAME
USERNAME="${1}"

# argument > parameter of COMMENT
shift
COMMENT="${@}"

# generate password
PASSWORD=$( date +%s%N | sha256sum | head -c10)

# create account
useradd -c "${COMMENT}" -m ${USERNAME}

# check for useradd exit status
if [[ "${?}" -ne 0 ]]
then
  echo 'That account could not be created'
  exit 1
fi

# set password

echo ${PASSWORD} | passwd --stdin ${USERNAME}

# check exit status of passwd
if [[ "${?}" -ne 0 ]]
then
  echo 'The password for the account could not be set'
  exit 1
fi

# force password change
passwd -e ${USERNAME}

# Display the info for output
echo
echo 'username'
echo ${USERNAME}
echo
echo 'password'
echo ${PASSWORD}
echo
echo 'host'
echo ${HOSTNAME}
echo
exit 0
